### ISSUE TITLE
Call $this->receive() twice in Connection::connect()

### ISSUE THREAD

**Issue by dfeyer** [repejota/phpnats#57]
Maybe my misunderstanding of the Nats protocol, but why did we call `$this->receive();` twice in Connection::connect() ?

```
public function connect($timeout = null)
{
    $this->timeout = $timeout;
    $this->streamSocket = $this->getStream($this->options->getAddress(), $timeout);
    $msg = 'CONNECT '.$this->options;
    $this->send($msg);

    $response = $this->receive();

    $this->ping();
    $response = $this->receive();

    if ($response !== "PONG") {
        if (strpos($response, '-ERR')!== false) {
            throw new \Exception("Failing connection: $response");
        }
    }
}
```

**Comment by dfeyer** [comment]
Can this one related to https://github.com/repejota/phpnats/issues/58 ?

**Comment by repejota** [comment]
No it is not related.
I made this as i was expecting INFO after a connect ( http://nats.io/documentation/internals/nats-protocol/#description:4b9a176fc3df6b183e7b5ba0c60737ef) 

Then i am sending a PING so i need to receive a PONG. That's why i have two receives.

Not sure if this is the correct way, but I will test it carefully once i finish the new test suite on #60
Gonna be soon 😉 

Did you found any problems with this behaviour?

**Comment by dfeyer** [comment]
> Did you found any problems with this behaviour?

Not directly, but by reading it sounds a bit strange. But protocol wise it sounds OK. Maybe we can just skip the creation of the first $response variable (not used, so no needs, a bit a micro optimisation), and add a small comment to help other people looking at this.

**Comment by repejota** [comment]
Sounds good. 
I will leave this open to work on it after i finish #60
